
name: Reusable dan deploy workflow

on:
  workflow_call:
    inputs:
      dotnet_version:
        type: string
        required: false
        default: '8.0.x'
      build_configuration:
        type: string
        default: 'Release'
        required: false
      root_solution_path:
        type: string
        default: './'
        required: false
      artifact_name:
        type: string
        default: 'artifact'
        required: false
      function_project_path:
        type: string
        required: true
    secrets:
      function_app_name:
        required: true
      publish_profile:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
      - name: 'Dotnet restore, build & test'
        run: |
          dotnet restore
          dotnet build --no-restore
          dotnet test --no-build --verbosity normal
        working-directory: ${{ inputs.root_solution_path }}
      - name: Dotnet build and publish Function App with configuration '${{ inputs.build_configuration }}'
        run: |
          dotnet build --configuration '${{ inputs.build_configuration }}'
          dotnet publish -c '${{ inputs.build_configuration }}' --no-restore -o './published-app'
        working-directory: ${{ inputs.function_project_path }}
      - name: Upload artifact '${{ inputs.artifact_name }}'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.function_project_path }}/published-app
          include-hidden-files: true
  
  deploy-dev:
    runs-on: ubuntu-latest
    environment: 'dev'
    needs: [build]
    steps:
      - name: 'Download artifact for dev'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: './downloaded-app'
      - name: 'Deploy artifact to dev'
        uses: azure/functions-action@v1
        with:
          app-name: ${{secrets.function_app_name}}
          package: './downloaded-app'
          sku: 'flexconsumption'
          publish-profile: ${{secrets.publish_profile}}  
  
  deploy-staging:   
    runs-on: ubuntu-latest
    environment: 'staging'
    needs: [deploy-dev]
    steps:
      - name: 'Download artifact for staging'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: './downloaded-app'
      - name: 'Deploy artifact to staging'
        uses: azure/functions-action@v1
        with:
          app-name: ${{secrets.function_app_name}}
          package: './downloaded-app'
          sku: 'flexconsumption'
          publish-profile: ${{secrets.publish_profile}} 

  deploy-production:
    runs-on: ubuntu-latest
    environment: 'prod'
    needs: [deploy-staging]
    steps:
      - name: 'Download artifact for deploy to production'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: './downloaded-app'
      - name: 'Deploy artifact to prod'
        uses: azure/functions-action@v1
        with:
          app-name: ${{secrets.function_app_name}}
          package: './downloaded-app'
          sku: 'flexconsumption'
          publish-profile: ${{secrets.publish_profile}}
        
